# environment.yml for GTB project
# This conda environment supports data ingestion scripts that fetch
# preliminary datasets (heat, pollution, demographics, temperature,
# elevation, land cover, air quality, sea level rise, etc.)

name: gtb-env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - requests
  - python-dotenv     # For loading .env credentials
  - geopandas         # Core geospatial data handling
  - fiona             # Required backend for reading/writing vector data
  - shapely           # Geometry operations (used by geopandas)
  - pyproj            # Coordinate reference systems (CRS)
  - pyogrio           # Fast vector I/O for geopandas
  - rasterio          # Raster data handling (e.g., NDVI tiles)
  - osmnx             # OpenStreetMap downloads (used for parks/infrastructure)
  - mercantile        # Tile coordinate conversion for satellite tiles
  - tqdm              # For progress bars
  - pip:
      - tqdm          # Ensures latest version from PyPI if needed
