# environment.yml for GTB project
# This conda environment supports data ingestion scripts that fetch
# preliminary datasets (heat, pollution, demographics, temperature,
# elevation, land cover, air quality, sea level rise, etc.)

name: gtb-env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - requests
  - python-dotenv
  - mercantile
  - geopandas
  - fiona
  - shapely
  - pyproj
  - pyogrio
  - rasterio
  - osmnx
  - tqdm
  - pip:
      - tqdm  # ensure the latest tqdm if conda-forge’s is out of date
